#!/usr/bin/env python

##############################################################################
# Python imports.
from datetime import datetime
from pathlib import Path

##############################################################################
# Jinja2 imports.
from jinja2 import Environment, FileSystemLoader

##############################################################################
# ng2web imports
from ng2web import __version__ as ng2web_version

##############################################################################
# NGDB imports.
from ngdb import NortonGuide
from ngdb import __version__ as ngdb_version


##############################################################################
def main() -> None:
    """The main entry point."""
    env = Environment(loader=FileSystemLoader("templates/index"))
    env.globals = {
        "guides": [NortonGuide(guide) for guide in sorted(Path("guides").glob("*.ng"))],
        "generator": f"ng2web v{ng2web_version} (ngdb v{ngdb_version})",
        "generation_time": datetime.now(),
    }
    Path("docs/index.html").open("w", encoding="utf8").write(
        env.get_template("index.html").render()
    )
    Path("docs/index.css").open("w", encoding="utf8").write(
        env.get_template("index.css").render()
    )


##############################################################################
if __name__ == "__main__":
    main()
